// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNTloSP9vbRgwQzwRh5bYkTmyBf5joSQ0',
    appId: '1:1016210308502:web:92a575e18ec7f77cca31b7',
    messagingSenderId: '1016210308502',
    projectId: 'email-authentication-bad06',
    authDomain: 'email-authentication-bad06.firebaseapp.com',
    storageBucket: 'email-authentication-bad06.appspot.com',
    measurementId: 'G-TQCNBZZ996',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHbf8dWqHolArZ4FTlhNvbEDQJ_FGt014',
    appId: '1:1016210308502:android:4852a5293a124055ca31b7',
    messagingSenderId: '1016210308502',
    projectId: 'email-authentication-bad06',
    storageBucket: 'email-authentication-bad06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3eqRqPVSH7LoRauOILDQGo0fWF-e98Lc',
    appId: '1:1016210308502:ios:4a2f7c1cc0de54b4ca31b7',
    messagingSenderId: '1016210308502',
    projectId: 'email-authentication-bad06',
    storageBucket: 'email-authentication-bad06.appspot.com',
    iosClientId: '1016210308502-39tnkrijkh0o1dim3scgiom0g3glnf3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3eqRqPVSH7LoRauOILDQGo0fWF-e98Lc',
    appId: '1:1016210308502:ios:4a2f7c1cc0de54b4ca31b7',
    messagingSenderId: '1016210308502',
    projectId: 'email-authentication-bad06',
    storageBucket: 'email-authentication-bad06.appspot.com',
    iosClientId: '1016210308502-39tnkrijkh0o1dim3scgiom0g3glnf3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailAuth',
  );
}
